# Generated by Django 6.0 on 2025-12-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='office_type',
            field=models.CharField(choices=[('ADMISSIONS', 'Admissions'), ('MEDICAL', 'Medical'), ('DEPARTMENT', 'Department'), ('BURSARY', 'Bursary'), ('LIBRARY', 'Library'), ('FACULTY', 'Faculty'), ('REGISTRY', 'Registry')], max_length=20),
        ),
    ]
