# Generated by Django 6.0 on 2025-12-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_officerprofile_is_onboarded_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='college',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
    ]
