# Generated by Django 6.0 on 2026-01-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_college_studentprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='office_type',
            field=models.CharField(choices=[('ADMISSIONS', 'Admissions'), ('MEDICAL', 'Medical'), ('DEPARTMENT', 'Department'), ('REGISTRY', 'Registry')], default='REGISTRY', max_length=20),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='office_type',
            field=models.CharField(choices=[('ADMISSIONS', 'Admissions'), ('MEDICAL', 'Medical'), ('DEPARTMENT', 'Department'), ('REGISTRY', 'Registry')], max_length=20),
        ),
    ]
