# Generated by Django 6.0 on 2025-12-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(choices=[('ADMISSIONS', 'Admissions'), ('MEDICAL', 'Medical'), ('DEPARTMENT', 'Department'), ('BURSARY', 'Bursary'), ('LIBRARY', 'Library'), ('FACULTY', 'Faculty')], max_length=20)),
                ('document_type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('accepted_formats', models.CharField(default='.pdf,.jpg,.jpeg,.png', max_length=255)),
                ('max_file_size', models.IntegerField(default=5000000)),
            ],
        ),
    ]
