# Generated by Django 6.0 on 2026-01-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_documentrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceitem',
            name='office_type',
            field=models.CharField(choices=[('ADMISSIONS', 'Admissions'), ('MEDICAL', 'Medical'), ('DEPARTMENT', 'Department')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='office_type',
            field=models.CharField(choices=[('ADMISSIONS', 'Admissions'), ('MEDICAL', 'Medical'), ('DEPARTMENT', 'Department')], max_length=20),
        ),
    ]
